"""add_document_generations_session_owned

Revision ID: 9f49ed675936
Revises: bf5378fd5abc
Create Date: 2026-05-30 18:26:11.407618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f49ed675936'
down_revision: Union[str, Sequence[str], None] = 'bf5378fd5abc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_generations', sa.Column('session_id', sa.UUID(), nullable=False, comment='Session that owns this documentation copy'))
    op.alter_column('document_generations', 'source_id',
               existing_type=sa.UUID(),
               comment='GitHub source this documentation was generated from',
               existing_comment='GitHub source being documented (primary binding for caching)',
               existing_nullable=False)
    op.alter_column('document_generations', 'user_id',
               existing_type=sa.UUID(),
               comment='User who owns this record',
               existing_comment='User who initiated the generation (for ownership verification)',
               existing_nullable=False)
    op.alter_column('document_generations', 'generated_markdown',
               existing_type=sa.TEXT(),
               comment='Complete generated markdown documentation (max ~200KB)',
               existing_comment='Complete generated markdown documentation (max ~100KB)',
               existing_nullable=True)
    op.drop_constraint(op.f('uq_doc_gen_source_id'), 'document_generations', type_='unique')
    op.create_index(op.f('ix_document_generations_session_id'), 'document_generations', ['session_id'], unique=False)
    op.create_unique_constraint('uq_doc_gen_session_source', 'document_generations', ['session_id', 'source_id'])
    op.create_foreign_key(None, 'document_generations', 'chat_sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_column('document_generations', 'triggered_by_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_generations', sa.Column('triggered_by_session_id', sa.UUID(), autoincrement=False, nullable=True, comment='UUID of the session that first triggered this generation. Stored as plain metadata — not a FK. Access is derived from source_id via chat_session_sources, not from this field.'))
    op.drop_constraint(None, 'document_generations', type_='foreignkey')
    op.drop_constraint('uq_doc_gen_session_source', 'document_generations', type_='unique')
    op.drop_index(op.f('ix_document_generations_session_id'), table_name='document_generations')
    op.create_unique_constraint(op.f('uq_doc_gen_source_id'), 'document_generations', ['source_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('document_generations', 'generated_markdown',
               existing_type=sa.TEXT(),
               comment='Complete generated markdown documentation (max ~100KB)',
               existing_comment='Complete generated markdown documentation (max ~200KB)',
               existing_nullable=True)
    op.alter_column('document_generations', 'user_id',
               existing_type=sa.UUID(),
               comment='User who initiated the generation (for ownership verification)',
               existing_comment='User who owns this record',
               existing_nullable=False)
    op.alter_column('document_generations', 'source_id',
               existing_type=sa.UUID(),
               comment='GitHub source being documented (primary binding for caching)',
               existing_comment='GitHub source this documentation was generated from',
               existing_nullable=False)
    op.drop_column('document_generations', 'session_id')
    # ### end Alembic commands ###