"""add_document_generations

Revision ID: bf5378fd5abc
Revises: 8d7848471a4d
Create Date: 2026-05-30 02:03:10.053023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf5378fd5abc'
down_revision: Union[str, Sequence[str], None] = '8d7848471a4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum('pending', 'generating', 'completed', 'failed', 'cancelled', name='documentgenerationstatus').create(op.get_bind())
    op.create_table('document_generations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False, comment='GitHub source being documented (primary binding for caching)'),
    sa.Column('user_id', sa.UUID(), nullable=False, comment='User who initiated the generation (for ownership verification)'),
    sa.Column('triggered_by_session_id', sa.UUID(), nullable=True, comment='UUID of the session that first triggered this generation. Stored as plain metadata — not a FK. Access is derived from source_id via chat_session_sources, not from this field.'),
    sa.Column('status', postgresql.ENUM('pending', 'generating', 'completed', 'failed', 'cancelled', name='documentgenerationstatus', create_type=False), nullable=False),
    sa.Column('progress_percent', sa.Integer(), nullable=False, comment='0–100 progress for SSE updates'),
    sa.Column('generated_markdown', sa.Text(), nullable=True, comment='Complete generated markdown documentation (max ~100KB)'),
    sa.Column('sections_metadata', sa.JSON(), nullable=True, comment='Section outline + usage metadata: {sections: [{title, level, char_start, char_end}], generated_model, input_tokens, output_tokens, estimated_cost_usd, generation_time_seconds}'),
    sa.Column('error_message', sa.String(length=500), nullable=True, comment='Error message if generation failed'),
    sa.Column('config', sa.JSON(), nullable=False, comment='Generation config: {model, style, detail_level, include_apis, include_examples, include_architecture_diagram, force_regenerate}'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('progress_percent >= 0 AND progress_percent <= 100', name='ck_progress_range'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', name='uq_doc_gen_source_id')
    )
    op.create_index(op.f('ix_document_generations_created_at'), 'document_generations', ['created_at'], unique=False)
    op.create_index(op.f('ix_document_generations_id'), 'document_generations', ['id'], unique=False)
    op.create_index(op.f('ix_document_generations_source_id'), 'document_generations', ['source_id'], unique=False)
    op.create_index(op.f('ix_document_generations_user_id'), 'document_generations', ['user_id'], unique=False)
    op.create_foreign_key(None, 'chat_sessions', 'chat_messages', ['last_compacted_message_id'], ['id'], ondelete='SET NULL', use_alter=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_document_generations_user_id'), table_name='document_generations')
    op.drop_index(op.f('ix_document_generations_source_id'), table_name='document_generations')
    op.drop_index(op.f('ix_document_generations_id'), table_name='document_generations')
    op.drop_index(op.f('ix_document_generations_created_at'), table_name='document_generations')
    op.drop_table('document_generations')
    sa.Enum('pending', 'generating', 'completed', 'failed', 'cancelled', name='documentgenerationstatus').drop(op.get_bind())
    # ### end Alembic commands ###